theme: jekyll-theme-minimal
title: beeradvocate.com, what kind of raters does the website attract ?
style="background-color: #a4f9ef7F" 
description: Website for the AnalyTeam project in ADA 2022
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Bibliography
    url: bibliography
