theme: jekyll-theme-minimal
title: BeerAdvocate, what kind of raters does the website attract?
#description: Data Story made by Juliette Parchet, Albin Vernhes, Henrique Gameiro and Farouk Boukil
#show_downloads: True
#navigation:
#  - title: Home
#    url: /
#  - title: Bibliography
#    url: bibliography
