theme: jekyll-theme-minimal
title: BeerAdvocate, what kind of raters does the website attract?
description: ''
#show_downloads: True
#navigation:
#  - title: Home
#    url: /
#  - title: Bibliography
#    url: bibliography
