theme: jekyll-theme-minimal
title: BeerAdvocate, what kind of raters does the website attract?
description: Website for the AnalyTeam project in ADA 2022 - Juliette Parchet, Albin Vernhes, Henrique Gameiro, Farouk Boukil
show_downloads: True
