theme: jekyll-theme-minimal
title: beeradvocate.com, what kind of raters does the website attract ?
description: Website for the AnalyTeam project in ADA 2022
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
